### ISSUE TITLE
ModuleNotFoundError: No module named 'ranger'

### ISSUE THREAD

**Issue by xxjunxx** [mrvoh/HA-CapsNet#4]
I got this error when executing "torch_to_tf_serving.py". What package is ranger?

```
Traceback (most recent call last):
  File "torch_to_tf_serving.py", line 23, in <module>
    from text_class_learner import TextClassificationLearner
  File "/home/kpl/HA-CapsNet/text_class_learner.py", line 3, in <module>
    from ranger import Ranger
ModuleNotFoundError: No module named 'ranger'
```

**Comment by xxjunxx** [comment]
Can I download pretrained model `HCapsNet.pt`
